#!/bin/bash
# Correctness regression check: builds HipSTR-MT (if needed), then runs it
# against two self-contained fixtures at several different --threads values,
# diffing every run's output against a committed golden VCF using
# compare_vcf_tolerant.py.
#
# This is the primary correctness check for this fork, and specifically
# targets its core claim: that parallelizing HipSTR doesn't change what it
# genotypes. Diffing every thread count against the SAME golden VCF checks
# both things a reviewer would ask about in one pass -- (a) correctness vs.
# the unmodified upstream gymrek-lab/HipSTR tool the golden VCFs were
# generated by (see README.md's Correctness section), and (b) that
# --threads 1/2/4/8 (whichever are requested) all agree with each other,
# since they all have to agree with the same golden file.
#
# The two fixtures cover different risks:
#
#   test/pgo/          Breadth: a real ~1Mb chr20 STR locus cluster, 654 loci,
#                      matching FASTA, and 2 subsetted sample BAMs -- the same
#                      fixture `make pgo` trains against.
#
#   test/homopolymer/  Depth: one locus, deliberately chosen because its
#                      alignment paths are near-degenerate. A 20bp homopolymer
#                      T-repeat (chr2:33759762 in hg19, shifted into a 10kb
#                      contig so the fixture stays small), from NA12892.
#                      Loci like this are where tiny floating-point
#                      differences change which candidate alleles get
#                      discovered, which flips the genotype call outright
#                      rather than perturbing a statistic. The 654-locus
#                      fixture above contains no such near-tied case and
#                      passed both before and after the bug this was added
#                      for -- see the comment on fast_exp_sum in
#                      src/mathops.cpp, and on MatrixChannel in
#                      src/SeqAlignment/HapAligner.h for an earlier instance
#                      of the same failure mode. Cheap insurance: 424KB.
#
# Usage: test/check_correctness.sh [THREADS...]
#   (default thread counts: 1 2 4 8, capped to nproc if the machine has fewer)
# Exit status: 0 if every requested thread count's output matches the golden
# VCF within tolerance, on both fixtures (no genotype changes, no >0.1% drift
# in derived statistics); nonzero otherwise. Suitable for CI.

set -uo pipefail
cd "$(dirname "$0")/.."

BIN=./HipSTR-MT

if [ ! -x "$BIN" ]; then
    echo "[check_correctness] $BIN not found, building..."
    make -j"$(nproc)" HipSTR-MT || exit 1
fi

if [ "$#" -gt 0 ]; then
    THREAD_COUNTS=("$@")
else
    NPROC=$(nproc)
    THREAD_COUNTS=()
    for t in 1 2 4 8; do
        [ "$t" -le "$NPROC" ] && THREAD_COUNTS+=("$t")
    done
    # Always test at least --threads 1, even on a single-CPU runner.
    [ "${#THREAD_COUNTS[@]}" -eq 0 ] && THREAD_COUNTS=(1)
fi

# Each fixture: name|dir|bams(comma separated, relative to dir)|fasta|bed|min-reads
FIXTURES=(
    "pgo|test/pgo|bams/sampleA.pgo.bam,bams/sampleB.pgo.bam|pgo_fixture.fa|pgo_fixture.bed|10"
    "homopolymer|test/homopolymer|bams/NA12892.homopolymer.bam|homopolymer_fixture.fa|homopolymer_fixture.bed|25"
)

OVERALL_STATUS=0
for FIXTURE in "${FIXTURES[@]}"; do
    IFS='|' read -r NAME DIR BAMS FASTA BED MIN_READS <<< "$FIXTURE"
    GOLDEN="$DIR/expected_output.vcf.gz"

    # Prefix each BAM with the fixture directory.
    BAM_ARG=""
    IFS=',' read -ra BAM_LIST <<< "$BAMS"
    for B in "${BAM_LIST[@]}"; do
        [ -n "$BAM_ARG" ] && BAM_ARG="$BAM_ARG,"
        BAM_ARG="$BAM_ARG$DIR/$B"
    done

    for T in "${THREAD_COUNTS[@]}"; do
        OUT="$DIR/actual_output_t${T}.vcf.gz"
        LOG="$DIR/actual_output_t${T}.log"

        echo "[check_correctness] [$NAME] --threads $T: running $BIN..."
        "$BIN" \
            --bams "$BAM_ARG" \
            --fasta "$DIR/$FASTA" \
            --regions "$DIR/$BED" \
            --str-vcf "$OUT" \
            --threads "$T" --min-reads "$MIN_READS" \
            --log "$LOG"
        if [ $? -ne 0 ]; then
            echo "[check_correctness] [$NAME] --threads $T: FAIL -- HipSTR-MT itself exited non-zero (kept $OUT / $LOG for inspection)"
            OVERALL_STATUS=1
            continue
        fi

        echo "[check_correctness] [$NAME] --threads $T: comparing against golden output..."
        python3 test/compare_vcf_tolerant.py "$GOLDEN" "$OUT"
        STATUS=$?

        if [ "$STATUS" -eq 0 ]; then
            echo "[check_correctness] [$NAME] --threads $T: PASS"
            rm -f "$OUT" "$LOG"
        else
            echo "[check_correctness] [$NAME] --threads $T: FAIL -- see findings above (kept $OUT / $LOG for inspection)"
            OVERALL_STATUS=1
        fi
        echo
    done
done

if [ "$OVERALL_STATUS" -eq 0 ]; then
    echo "[check_correctness] PASS on all fixtures across all thread counts tested: ${THREAD_COUNTS[*]}"
else
    echo "[check_correctness] FAIL"
fi
exit $OVERALL_STATUS
