#define HTS_CC "gcc"
#define HTS_CPPFLAGS "-I/home/porkc/HipSTR/lib/libdeflate -DHAVE_LIBDEFLATE"
#define HTS_CFLAGS "-g -Wall -O2 -fvisibility=hidden"
#define HTS_LDFLAGS "-fvisibility=hidden"
#define HTS_LIBS "-lz -lm -lbz2 -llzma -lcurl"
